apply plugin: libs.plugins.androidApplication.get().pluginId
apply plugin: libs.plugins.kotlinMultiplatform.get().pluginId
apply plugin: libs.plugins.composeMultiplatform.get().pluginId
apply plugin: libs.plugins.composeCompiler.get().pluginId

android {
    defaultConfig {
        applicationId = "com.tanda" + project.path.replace(':', '.')
    }
    buildTypes {
        release {
            minifyEnabled = false
        }
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}
