package com.tanda.core.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightColorScheme = lightColorScheme(
    primary = Primary500,
    onPrimary = Color.White,
    primaryContainer = Primary100,
    onPrimaryContainer = Primary900,
    inversePrimary = Primary200,
    secondary = Primary700,
    onSecondary = Color.White,
    secondaryContainer = Primary200,
    onSecondaryContainer = Primary950,
    tertiary = Accent600,
    onTertiary = Color.White,
    tertiaryContainer = Accent100,
    onTertiaryContainer = Accent900,
    error = ErrorLight,
    onError = OnErrorLight,
    errorContainer = ErrorContainerLight,
    onErrorContainer = OnErrorContainerLight,
    background = NeutralBackgroundLight,
    onBackground = OnNeutralBackgroundLight,
    surface = NeutralBackgroundLight,
    onSurface = OnNeutralBackgroundLight,
    surfaceVariant = SurfaceVariantLight,
    onSurfaceVariant = OnSurfaceVariantLight,
    surfaceTint = Primary500,
    inverseSurface = Color(0xFF2D3230),
    inverseOnSurface = Color(0xFFEFF1EE),
    outline = OutlineLight,
    outlineVariant = OutlineVariantLight,
    scrim = Color.Black,
)

val DarkColorScheme = darkColorScheme(
    primary = Primary300,
    onPrimary = Primary900,
    primaryContainer = Primary700,
    onPrimaryContainer = Primary100,
    inversePrimary = Primary600,
    secondary = Primary200,
    onSecondary = Primary800,
    secondaryContainer = Primary600,
    onSecondaryContainer = Primary50,
    tertiary = Accent300,
    onTertiary = Accent900,
    tertiaryContainer = Accent700,
    onTertiaryContainer = Accent100,
    error = ErrorDark,
    onError = OnErrorDark,
    errorContainer = ErrorContainerDark,
    onErrorContainer = OnErrorContainerDark,
    background = NeutralBackgroundDark,
    onBackground = OnNeutralBackgroundDark,
    surface = NeutralBackgroundDark,
    onSurface = OnNeutralBackgroundDark,
    surfaceVariant = SurfaceVariantDark,
    onSurfaceVariant = OnSurfaceVariantDark,
    surfaceTint = Primary300,
    inverseSurface = Color(0xFFE1E3DF),
    inverseOnSurface = Color(0xFF2D3230),
    outline = OutlineDark,
    outlineVariant = OutlineVariantDark,
    scrim = Color.Black,
)
