[package]
name = "biometric-sdk"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]
path = "src/commonMain/rust/src/lib.rs"

[dependencies]
fs2 = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
uniffi = "0.32.0"
uuid = { version = "1.23.4", features = ["v4"] }
