[package]
name = "tanda-biometric-verification"
version = "0.1.0"
edition = "2024"

[lib]
name = "biometric_sdk"
crate-type = ["cdylib", "staticlib"]
path = "src/commonMain/rust/lib.rs"

[dependencies]
biometric-sdk-core = { package = "biometric-sdk", git = "https://github.com/DataInfosec/biometric-sdk", rev = "50cabd814ecef86285651e45b670e64b98f4d670", default-features = false, features = ["uniffi-bindings"] }
