[package]
name = "tanda-biometric-verification"
version = "0.1.0"
edition = "2024"

[lib]
name = "biometric_sdk"
crate-type = ["cdylib", "staticlib"]
path = "src/commonMain/rust/src/lib.rs"

[dependencies]
biometric-sdk-core = { package = "biometric-sdk", git = "https://github.com/DataInfosec/biometric-sdk", rev = "929a082bfb8e17ae85e349b126a1a2dd117e2105", default-features = false, features = ["uniffi-bindings"] }
